export const DUMMY_DATA = [
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  {
    id: JSON.stringify(Math.floor(10001232 * Math.random())),
    firstName: "John Doe",
    email: "johndoe@gmail.com",
    mobile: "9876543210",
    gender: "male",
    dob: "02/03/1998",
    status: "Active",
    courses: ["Maths", "Physics"],
  },
  
];
